### ISSUE TITLE
List class causes conflicts with established Bioconductor List class

### ISSUE THREAD

**Issue by LiNk-NY** [jabiru/tictoc#8]
Hi Sergei, @sizrailev

I hope you are well.
There have been a few issues reported in Bioconductor where the `List` class
in `tictoc` conflicts with the `List` class in `S4Vectors` and its
derivatives. Note that the latter have been around for over 12 years.

See a couple of examples here:
https://github.com/Bioconductor/Biostrings/issues/99#issuecomment-1513513946
https://github.com/waldronlab/MultiAssayExperiment/issues/321

Hervé has worked on a few workarounds to add a layer above the conflicting
print method so that the appropriate one gets called.

Hervé may want to comment here but it would be great to be able to avoid
conflicts coming from the `List` class in this package.

Thank you,
Marcel

cc: @hpages

**Comment by sizrailev** [comment]
Hi @LiNk-NY and @hpages! Thanks for your comments! The Stack and List classes were not exported until Sep 2022, even though they have existed since 2014. I renamed List to StackList in #9 since it's a stack implemented as a list, so there should be no more conflicts in naming.

**Comment by LiNk-NY** [comment]
Thank you for taking care of this @sizrailev !
